### ISSUE TITLE
Add ability to edit default timeout

### ISSUE THREAD

**Issue by Lioness100** [TypeCtrl/plex#22]
Hi! I understand you might be past maintaining this repo, but in case you're not, could you consider providing a way to edit the default timeout?

**Comment by Lioness100** [comment]
Thank you!

**Comment by scttcper** [comment]
You should be able to set the timeout in the class or just modify the class i guess. I thought about adding a request object to every async function but that seemed extreme. The python version this is based on obviously has different ways of changing global constants.
